accessing
expectedException: anObject

   expectedException := anObject